project_id = "dkykhgjdshlwihvqtgfx"

[functions.google-vision-ocr]
verify_jwt = false

[functions.bloodvista-chat]
verify_jwt = false

[functions.radiology-analysis]
verify_jwt = false

[functions.blood-analysis-enhance]
verify_jwt = false
